name: Test PowerShell on Ubuntu
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2 # Update this to the latest version
      - name: Set up Node.js
        uses: actions/setup-node@v2 # Add this step to set up Node.js 16
        with:
          node-version: 16
      - name: Perform a Pester test from the command-line
        run: pwsh -Command "Test-Path resultsfile.log | Should -Be $true"
      - name: Perform Pester tests from the Tests.ps1 files
        run: |
          $testFiles = Get-ChildItem -Path tests -Filter "*.Tests.ps1" -File
          foreach ($file in $testFiles) {
            Invoke-Pester -Path $file.FullName -OutputFile "testResults_$($file.BaseName).xml" -OutputFormat NUnitXml
          }
